# Generated by Django 3.2.7 on 2021-09-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210910_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.administradores'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiantes'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='articulosID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.articulos'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.estudiantes'),
        ),
    ]
